CREATE TABLE "box_content_headers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "box_content_headers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"box_id" integer NOT NULL,
	"destination_text" text,
	"ready_at" timestamp with time zone,
	"returned_at" timestamp with time zone,
	"remarks" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"created_by" text,
	"updated_at" timestamp with time zone DEFAULT now(),
	"updated_by" text
);
--> statement-breakpoint
CREATE TABLE "box_content_lines" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "box_content_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"box_content_header_id" integer NOT NULL,
	"flask_id" integer NOT NULL,
	"remarks" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"created_by" text,
	"updated_at" timestamp with time zone DEFAULT now(),
	"updated_by" text
);
--> statement-breakpoint
CREATE TABLE "boxes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "boxes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"remarks" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"created_by" text,
	"updated_at" timestamp with time zone DEFAULT now(),
	"updated_by" text
);
--> statement-breakpoint
CREATE TABLE "flask_ref_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flask_ref_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"created_by" text,
	"updated_at" timestamp with time zone DEFAULT now(),
	"updated_by" text
);
--> statement-breakpoint
CREATE TABLE "flasks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flasks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"remarks" text,
	"broken_at" timestamp with time zone,
	"low_pressure_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"created_by" text,
	"updated_at" timestamp with time zone DEFAULT now(),
	"updated_by" text
);
--> statement-breakpoint
CREATE TABLE "flasks_ref" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flasks_ref_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"original_flask_id" integer NOT NULL,
	"new_flask_id" integer NOT NULL,
	"flask_ref_type_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"created_by" text,
	"updated_at" timestamp with time zone DEFAULT now(),
	"updated_by" text
);
--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"is_admin" boolean DEFAULT false NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "box_content_headers" ADD CONSTRAINT "box_content_headers_box_id_boxes_id_fk" FOREIGN KEY ("box_id") REFERENCES "public"."boxes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "box_content_lines" ADD CONSTRAINT "box_content_lines_box_content_header_id_box_content_headers_id_fk" FOREIGN KEY ("box_content_header_id") REFERENCES "public"."box_content_headers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "box_content_lines" ADD CONSTRAINT "box_content_lines_flask_id_flasks_id_fk" FOREIGN KEY ("flask_id") REFERENCES "public"."flasks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flasks_ref" ADD CONSTRAINT "flasks_ref_original_flask_id_flasks_id_fk" FOREIGN KEY ("original_flask_id") REFERENCES "public"."flasks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flasks_ref" ADD CONSTRAINT "flasks_ref_new_flask_id_flasks_id_fk" FOREIGN KEY ("new_flask_id") REFERENCES "public"."flasks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flasks_ref" ADD CONSTRAINT "flasks_ref_flask_ref_type_id_flask_ref_type_id_fk" FOREIGN KEY ("flask_ref_type_id") REFERENCES "public"."flask_ref_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "boxes_index_0" ON "boxes" USING btree ("name");--> statement-breakpoint
CREATE INDEX "flasks_index_0" ON "flasks" USING btree ("name");--> statement-breakpoint
CREATE INDEX "account_userId_idx" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_userId_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "verification" USING btree ("identifier");